"""Sample test — auto-generated by goal."""

from __future__ import annotations

from pathlib import Path

import pytest

from pyqual.config import GateConfig
from pyqual.gates import GateSet


def test_placeholder() -> None:
    """Placeholder test to verify the test setup works."""
    assert True


def test_import() -> None:
    """Verify the main package can be imported."""
    import pyqual  # noqa: F401


def test_llm_exports_use_llx_when_available() -> None:
    """Verify pyqual re-exports the llx LLM API when llx is installed."""
    llx = pytest.importorskip("llx")
    import pyqual

    assert pyqual.DEFAULT_MAX_TOKENS == llx.DEFAULT_MAX_TOKENS
    assert pyqual.LLM is llx.LLM
    assert pyqual.LLMResponse is llx.LLMResponse
    assert pyqual.get_api_key is llx.get_api_key
    assert pyqual.get_llm is llx.get_llm
    assert pyqual.get_llm_model is llx.get_llm_model


from pyqual.cli_run_helpers import extract_stage_summary as _ess


class TestExtractStageSummary:
    def test_pytest_passed(self) -> None:
        d = _ess("test", "5 passed in 1.4s", "")
        assert d["passed"] == 5

    def test_pytest_failed(self) -> None:
        d = _ess("test", "3 passed, 2 failed in 2.1s", "")
        assert d["passed"] == 3
        assert d["failed"] == 2

    def test_pytest_no_match_returns_empty(self) -> None:
        assert _ess("test", "collecting ...", "") == {}

    def test_ruff_errors(self) -> None:
        assert _ess("lint", "Found 7 errors.", "")["lint_errors"] == 7

    def test_ruff_clean(self) -> None:
        assert _ess("lint", "All checks passed!", "")["lint_errors"] == 0

    def test_prefact_tickets(self) -> None:
        assert _ess("prefact", "Total issues: 71 active, 0 completed", "")["tickets"] == 71

    def test_prefact_zero_tickets(self) -> None:
        assert _ess("prefact", "Total issues: 0 active, 5 completed", "")["tickets"] == 0

    def test_validate_cc_critical(self) -> None:
        d = _ess("validate", "cc: 3.1\ncritical: 0", "")
        assert d["cc"] == 3.1
        assert d["critical"] == 0

    def test_llx_fix_model(self) -> None:
        d = _ess("fix", "Selected: balanced → claude-sonnet-4-20250514\n", "")
        assert d["model"] == "claude-sonnet-4-20250514"

    def test_llx_fix_files_changed(self) -> None:
        assert _ess("fix", "3 files changed, 42 insertions(+)", "")["files_changed"] == 3

    def test_mypy_errors(self) -> None:
        d = _ess("mypy", "", "Found 4 errors in 2 files (checked 12 source files)")
        assert d["mypy_errors"] == 4
        assert d["mypy_files"] == 2

    def test_bandit_severity(self) -> None:
        d = _ess("bandit", "High: 1  Medium: 3  Low: 5", "")
        assert d["bandit_high"] == 1
        assert d["bandit_medium"] == 3
        assert d["bandit_low"] == 5

    def test_empty_output_no_crash(self) -> None:
        assert _ess("analyze", "", "") == {}

    def test_uses_stderr_as_fallback(self) -> None:
        assert _ess("test", "", "5 passed in 0.9s")["passed"] == 5


def test_gate_set_reads_project_toon_artifacts(tmp_path: Path) -> None:
    """Verify metrics are collected from dotted toon files in project/."""
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    (project_dir / "analysis.toon.yaml").write_text(
        "# code2llm | 11f 2692L | python:10,shell:1\n# CC̄=4.9 | critical:2/117 | dups:0 | cycles:0\n"
    )
    (project_dir / "validation.toon.yaml").write_text(
        "# vallm batch | 64f | 31✓ 3⚠ 0✗\nSUMMARY:\n  scanned: 64  passed: 31 (48.4%)  warnings: 3  errors: 0  unsupported: 33\n"
    )
    pyqual_dir = tmp_path / ".pyqual"
    pyqual_dir.mkdir()
    (pyqual_dir / "coverage.json").write_text('{"totals": {"percent_covered": 28.9}}')

    gate_set = GateSet([
        GateConfig(metric="cc", operator="le", threshold=15),
        GateConfig(metric="vallm_pass", operator="ge", threshold=90),
        GateConfig(metric="coverage", operator="ge", threshold=80),
    ])

    metrics = gate_set._collect_metrics(tmp_path)

    assert metrics["cc"] == 4.9
    assert metrics["critical"] == 2.0
    assert metrics["vallm_pass"] == 48.4
    assert metrics["coverage"] == 28.9


def test_gate_set_derives_completion_rate(tmp_path: Path) -> None:
    """Verify completion_rate is derived from gate results."""
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    (project_dir / "analysis.toon.yaml").write_text(
        "# code2llm | 11f 2692L | python:10,shell:1\n# CC̄=4.9 | critical:2/117 | dups:0 | cycles:0\n"
    )
    (project_dir / "validation.toon.yaml").write_text(
        "# vallm batch | 64f | 31✓ 3⚠ 0✗\nSUMMARY:\n  scanned: 64  passed: 31 (48.4%)  warnings: 3  errors: 0  unsupported: 33\n"
    )
    pyqual_dir = tmp_path / ".pyqual"
    pyqual_dir.mkdir()
    (pyqual_dir / "coverage.json").write_text('{"totals": {"percent_covered": 28.9}}')

    gate_set = GateSet([
        GateConfig(metric="cc", operator="le", threshold=15),
        GateConfig(metric="vallm_pass", operator="ge", threshold=90),
        GateConfig(metric="coverage", operator="ge", threshold=80),
        GateConfig(metric="completion_rate", operator="ge", threshold=100),
    ])

    results = gate_set.check_all(tmp_path)
    completion_gate = next(r for r in results if r.metric == "completion_rate")

    assert completion_gate.value == pytest.approx(33.3333333333)
    assert completion_gate.passed is False
    assert gate_set.completion_percentage(tmp_path) == pytest.approx(33.3333333333)
