"""Sample test — auto-generated by goal."""

from pathlib import Path

from pyqual.config import GateConfig
from pyqual.gates import GateSet


def test_placeholder():
    """Placeholder test to verify the test setup works."""
    assert True


def test_import():
    """Verify the main package can be imported."""
    import pyqual  # noqa: F401


def test_gate_set_reads_project_toon_artifacts(tmp_path: Path):
    """Verify metrics are collected from dotted toon files in project/."""
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    (project_dir / "analysis.toon.yaml").write_text(
        "# code2llm | 11f 2692L | python:10,shell:1\n# CC̄=4.9 | critical:2/117 | dups:0 | cycles:0\n"
    )
    (project_dir / "validation.toon.yaml").write_text(
        "# vallm batch | 64f | 31✓ 3⚠ 0✗\nSUMMARY:\n  scanned: 64  passed: 31 (48.4%)  warnings: 3  errors: 0  unsupported: 33\n"
    )
    pyqual_dir = tmp_path / ".pyqual"
    pyqual_dir.mkdir()
    (pyqual_dir / "coverage.json").write_text('{"totals": {"percent_covered": 28.9}}')

    gate_set = GateSet([
        GateConfig(metric="cc", operator="le", threshold=15),
        GateConfig(metric="vallm_pass", operator="ge", threshold=90),
        GateConfig(metric="coverage", operator="ge", threshold=80),
    ])

    metrics = gate_set._collect_metrics(tmp_path)

    assert metrics["cc"] == 4.9
    assert metrics["critical"] == 2.0
    assert metrics["vallm_pass"] == 48.4
    assert metrics["coverage"] == 28.9
