flowchart TD
    examples__integration_example["examples.integration_example<br/>7 funcs"]
    examples__multi_gate_pipeline["examples.multi_gate_pipeline<br/>2 funcs"]
    examples__ticket_workflow["examples.ticket_workflow<br/>3 funcs"]
    pyqual__api["pyqual.api<br/>15 funcs"]
    pyqual__bulk_init["pyqual.bulk_init<br/>19 funcs"]
    pyqual__bulk_run["pyqual.bulk_run<br/>7 funcs"]
    pyqual__cli["pyqual.cli<br/>35 funcs"]
    pyqual__cli_bulk_cmds["pyqual.cli_bulk_cmds<br/>3 funcs"]
    pyqual__config["pyqual.config<br/>8 funcs"]
    pyqual__fix_tools["pyqual.fix_tools<br/>16 funcs"]
    pyqual__gates["pyqual.gates<br/>11 funcs"]
    pyqual__github_tasks["pyqual.github_tasks<br/>3 funcs"]
    pyqual__pipeline["pyqual.pipeline<br/>26 funcs"]
    pyqual__plugins["pyqual.plugins<br/>116 funcs"]
    pyqual__profiles["pyqual.profiles<br/>2 funcs"]
    pyqual__report["pyqual.report<br/>18 funcs"]
    pyqual__run_parallel_fix["pyqual.run_parallel_fix<br/>10 funcs"]
    pyqual__tickets["pyqual.tickets<br/>7 funcs"]
    pyqual__tools["pyqual.tools<br/>15 funcs"]
    pyqual__validation["pyqual.validation<br/>9 funcs"]
    run_analysis["run_analysis<br/>2 funcs"]
    pyqual__cli ==>|14| pyqual__plugins
    examples__integration_example ==>|13| pyqual__api
    pyqual__cli_bulk_cmds ==>|6| pyqual__bulk_run
    pyqual__cli ==>|6| pyqual__tickets
    pyqual__config ==>|5| pyqual__tools
    examples__ticket_workflow ==>|4| pyqual__tickets
    pyqual__validation ==>|4| pyqual__tools
    pyqual__cli ==>|4| pyqual__config
    pyqual__cli ==>|4| pyqual__api
    pyqual__cli -->|3| pyqual__github_tasks
    pyqual__config -->|2| pyqual__profiles
    pyqual__api -->|2| pyqual__tools
    pyqual__cli -->|2| pyqual__profiles
    pyqual__cli -->|2| pyqual__validation
    pyqual__pipeline -->|2| pyqual__tools
    run_analysis -->|1| pyqual__config
    examples__ticket_workflow -->|1| pyqual__config
    examples__multi_gate_pipeline -->|1| pyqual__config
    pyqual__gates -->|1| pyqual__plugins
    pyqual__tickets -->|1| pyqual__config
    pyqual__cli_bulk_cmds -->|1| pyqual__bulk_init
    pyqual__api -->|1| pyqual__config
    pyqual__api -->|1| pyqual__profiles
    pyqual__run_parallel_fix -->|1| pyqual__fix_tools
    pyqual__bulk_run -->|1| pyqual__api
    pyqual__report -->|1| pyqual__plugins
    pyqual__report -->|1| pyqual__config
