flowchart TD
    Taskfile["Taskfile<br/>1 funcs"]
    examples__custom_gates["examples.custom_gates<br/>9 funcs"]
    examples__integration_example["examples.integration_example<br/>7 funcs"]
    examples__multi_gate_pipeline["examples.multi_gate_pipeline<br/>2 funcs"]
    examples__ticket_workflow["examples.ticket_workflow<br/>3 funcs"]
    project__map["project.map<br/>575 funcs"]
    pyqual__api["pyqual.api<br/>15 funcs"]
    pyqual__auto_closer["pyqual.auto_closer<br/>7 funcs"]
    pyqual__bulk["pyqual.bulk<br/>9 funcs"]
    pyqual__bulk_init["pyqual.bulk_init<br/>15 funcs"]
    pyqual__cli["pyqual.cli<br/>55 funcs"]
    pyqual__cli_bulk_cmds["pyqual.cli_bulk_cmds<br/>6 funcs"]
    pyqual__cli_run_helpers["pyqual.cli_run_helpers<br/>24 funcs"]
    pyqual__config["pyqual.config<br/>8 funcs"]
    pyqual__custom_fix["pyqual.custom_fix<br/>3 funcs"]
    pyqual__gate_collectors["pyqual.gate_collectors<br/>7 funcs"]
    pyqual__github_actions["pyqual.github_actions<br/>16 funcs"]
    pyqual__integrations["pyqual.integrations<br/>6 funcs"]
    pyqual__parallel["pyqual.parallel<br/>7 funcs"]
    pyqual__pipeline["pyqual.pipeline<br/>31 funcs"]
    pyqual__plugins["pyqual.plugins<br/>255 funcs"]
    pyqual__release_check["pyqual.release_check<br/>2 funcs"]
    pyqual__report["pyqual.report<br/>19 funcs"]
    pyqual__report_generator["pyqual.report_generator<br/>15 funcs"]
    pyqual__run_parallel_fix["pyqual.run_parallel_fix<br/>12 funcs"]
    pyqual__setup_deps["pyqual.setup_deps<br/>5 funcs"]
    pyqual__validation["pyqual.validation<br/>27 funcs"]
    run_analysis["run_analysis<br/>2 funcs"]
    pyqual__plugins ==>|60| project__map
    pyqual__run_parallel_fix ==>|47| Taskfile
    pyqual__cli ==>|32| project__map
    examples__custom_gates ==>|25| Taskfile
    run_analysis ==>|18| Taskfile
    examples__integration_example ==>|14| Taskfile
    examples__multi_gate_pipeline ==>|14| Taskfile
    pyqual__auto_closer ==>|14| Taskfile
    examples__ticket_workflow ==>|10| Taskfile
    pyqual__custom_fix ==>|10| Taskfile
    pyqual__config ==>|10| project__map
    pyqual__release_check ==>|8| Taskfile
    pyqual__plugins ==>|8| Taskfile
    pyqual__cli_bulk_cmds ==>|7| project__map
    pyqual__github_actions ==>|7| Taskfile
    pyqual__validation ==>|7| project__map
    examples__integration_example ==>|5| project__map
    pyqual__setup_deps ==>|5| Taskfile
    pyqual__report ==>|5| Taskfile
    examples__ticket_workflow ==>|4| project__map
    pyqual__pipeline ==>|4| project__map
    pyqual__api -->|3| project__map
    pyqual__cli_run_helpers -->|3| project__map
    pyqual__report_generator -->|2| Taskfile
    pyqual__bulk_init -->|2| project__map
    pyqual__gate_collectors -->|2| project__map
    pyqual__bulk -->|2| project__map
    pyqual__integrations -->|2| Taskfile
    pyqual__parallel -->|1| project__map
    pyqual__run_parallel_fix -->|1| project__map
    pyqual__release_check -->|1| project__map
